spring.application.name=AeroScale

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/AeroScale
spring.datasource.username=postgres
spring.datasource.password=Shadab4321$


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# accesstoken setting
app.jwt.secret=c2VjdXJlLWZsYXNoLXNhbGUtYXV0aC1zZXJ2aWNlLXNlY3JldC1rZXktY2hhbmdlLW1lLWlcuhnc75t94g3o14ruLXByb2R1Y3Rpb24tMjU2Yml0huihnyYGfeg9rygt674r7y3cgt497xo834gxyg
app.jwt.access-token-expiration-ms=900000
app.jwt.issuer=AeroScale-auth-service

#refreshToken setting
jwt.refresh-token-expiration-ms=604800000
jwt.refresh-token-byteLength=64
