spring.application.name=AeroScale

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/AeroScale
spring.datasource.username=postgres
spring.datasource.password=Shadab4321$


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# accesstoken setting
jwt.secret=c2VjdXJlLWZsYXNoLXNhbGUtYXV0aC1zZXJ2aWNlLXNlY3JldC1rZXktY2hhbmdlLW1lLWlcuhnc75t94g3o14ruLXByb2R1Y3Rpb24tMjU2Yml0huihnyYGfeg9rygt674r7y3cgt497xo834gxyg
jwt.access-token-expiration-ms=90000000
jwt.issuer=AeroScale-auth-service

#refreshToken setting
jwt.refresh-token-expiration-ms=604800000
jwt.refresh-token-byteLength=64


#"accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmOWEzMDNjMi1kOTc0LTQ2NDYtYjczYS00YTg0NTU3ZWQzMTIiLCJlbWFpbCI6InNlbGxlckBnbWFpbC5jb20iLCJyb2xlIjoiU0VMTEVSIiwiaXNzIjoiQWVyb1NjYWxlLWF1dGgtc2VydmljZSIsImlhdCI6MTc4NzI0MjI5NCwiZXhwIjoxNzg3MzMyMjk0fQ.f0CrJsoyFJjo1-zPL_cUM-LqerPx_VIUrWVvfYtC5SQ",
#"accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlZjMxYTlhMC02Yzg3LTRiYzYtYjNjNi02YThhODFkNzBmNTEiLCJlbWFpbCI6ImJ1eWVyQGdtYWlsLmNvbSIsInJvbGUiOiJCVVlFUiIsImlzcyI6IkFlcm9TY2FsZS1hdXRoLXNlcnZpY2UiLCJpYXQiOjE3ODcyNDI1MDksImV4cCI6MTc4NzMzMjUwOX0.RV3EzLlUo9lPZoi6S21Cbg_QFIboFYvXsqJzW188-Oc",
#"accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwNTRlNzdlZS00ZTU1LTQ4YWQtOTA0Yi1iODY3YjQzOWMxNWQiLCJlbWFpbCI6ImJ1eWVyMkBnbWFpbC5jb20iLCJyb2xlIjoiQlVZRVIiLCJpc3MiOiJBZXJvU2NhbGUtYXV0aC1zZXJ2aWNlIiwiaWF0IjoxNzg3MjQ1MDQ2LCJleHAiOjE3ODczMzUwNDZ9.mkT3_QKif_Iak-Q-VkZ2xH3_AiuTpNneINIeteDxgWw",
#eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlZjMxYTlhMC02Yzg3LTRiYzYtYjNjNi02YThhODFkNzBmNTEiLCJlbWFpbCI6ImJ1eWVyQGdtYWlsLmNvbSIsInJvbGUiOiJCVVlFUiIsImlzcyI6IkFlcm9TY2FsZS1hdXRoLXNlcnZpY2UiLCJpYXQiOjE3ODc0MTczNDQsImV4cCI6MTc4NzUwNzM0NH0.R8Nav1rVx47naR0h8c_FxdAxeL7wFag1gb0aeDEBQGA



